version: 2

seeds:
  - name: ref_companies
    description: >
      Reference table containing mock companies used to enrich user data
      with company names and identifiers.
    columns:
      - name: company_id
        description: Unique identifier of the company
        tests:
          - not_null
          - unique

      - name: company_name
        description: Name of the company
        tests:
          - not_null
